### ISSUE TITLE
service_presenter.name does not appear in the generated html

### ISSUE THREAD

**Issue by sanyco86** [razum2um/lurker#112]
https://github.com/razum2um/lurker/blob/master/lib/lurker/templates/layouts/application.html.erb#L26  ```<%= @service_presenter.name %> ``` в сгенерированных html пустой, то есть генерируется
 html ``` <a class="navbar-brand" href="/lurker"></a>```
  а должен быть
 ```<a class="navbar-brand" href="/lurker">ExampleApp</a>```
в ExampleApp.service.yml   ```:name: ExampleApp``` присутствует

**Comment by razum2um** [comment]
@sanyco86 thanks for bug-report
fixed with https://github.com/razum2um/lurker/pull/116
released in 0.6.12

**note** you'll have to recreate service.yml or fix it to use strings, not symbols in keys
